name: staggered_loader
description: >-
  A Flutter widget that avoids the flash of shimmer for fast futures by
  delaying the loader until a UX-informed deadline elapses.
version: 0.0.1
homepage: https://github.com/raveesh-me/flutter_staggered_loader
repository: https://github.com/raveesh-me/flutter_staggered_loader
issue_tracker: https://github.com/raveesh-me/flutter_staggered_loader/issues

topics:
  - loader
  - shimmer
  - future
  - ux
  - performance

environment:
  sdk: ^3.13.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
